import Head from 'next/head'
import { CardCharacter } from '../src/components/CardCharater/CardCharacter'
import { Header } from '../src/components/Header/Header'
import styles from "./styles/Characters.module.scss"


export default function Characters() {

  return (
      <div className={styles.Characters}>
        <Head>
          <title>Multiverse of madness - Doctor Strange</title>
          <meta name="description" content="Generated by create next app" />
          
        </Head>
        <Header/>
        <section className={styles.section}>
          <div className={styles.name}><h1>SCARLET<br/>WITCH</h1></div>
          <div className={styles.characters}>
            <CardCharacter></CardCharacter>
            <img src="/images/Image-Character.png" alt=""/>
          </div>
        </section>
      </div>
  )
}


